version: "3.8"

services:
  postgesql:
    image: postgres:12-alpine
    container_name: user_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    networks:
      - user_network

networks:
  user_network:
    driver: bridge